### ISSUE TITLE
MCE in KT

### ISSUE THREAD

**Issue by compartia** [kestreltechnology/sonar-kt-advance#3]
Exception in thread "main" com.kt.advance.season.SeasonGreetings$MerryChristmasException
	at com.kt.advance.season.SeasonGreetings.main(SeasonGreetings.java:24)

**Comment by mrbkt** [comment]
Confirmed, and re-gifting for your enjoyment.  

```{java}
Exception in thread "main" 
   com.kt.advance.season.SeasonGreetings$HappyNewYearException
  at com.kt.advance.season.SeasonGreetings.main(SeasonGreetings.java:2017)
Caused by: com.kt.advance.project.Dovecot$AnalysisUpdate
  at com.dropbox.folder.AZKTSQ(dovecot..zip:20161230)
```
